/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ColSetting: (typeof import("./../components/ProTable/components/ColSetting.vue"))["default"];
    ECharts: (typeof import("./../components/ECharts/index.vue"))["default"];
    ElAside: (typeof import("element-plus/es"))["ElAside"];
    ElBadge: (typeof import("element-plus/es"))["ElBadge"];
    ElBreadcrumb: (typeof import("element-plus/es"))["ElBreadcrumb"];
    ElBreadcrumbItem: (typeof import("element-plus/es"))["ElBreadcrumbItem"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCol: (typeof import("element-plus/es"))["ElCol"];
    ElColorPicker: (typeof import("element-plus/es"))["ElColorPicker"];
    ElContainer: (typeof import("element-plus/es"))["ElContainer"];
    ElDatePicker: (typeof import("element-plus/es"))["ElDatePicker"];
    ElDescriptions: (typeof import("element-plus/es"))["ElDescriptions"];
    ElDescriptionsItem: (typeof import("element-plus/es"))["ElDescriptionsItem"];
    ElDialog: (typeof import("element-plus/es"))["ElDialog"];
    ElDivider: (typeof import("element-plus/es"))["ElDivider"];
    ElDrawer: (typeof import("element-plus/es"))["ElDrawer"];
    ElDropdown: (typeof import("element-plus/es"))["ElDropdown"];
    ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"];
    ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"];
    ElementItem: (typeof import("./../components/ProForm/components/ElementItem.vue"))["default"];
    ElEmpty: (typeof import("element-plus/es"))["ElEmpty"];
    ElFooter: (typeof import("element-plus/es"))["ElFooter"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElHeader: (typeof import("element-plus/es"))["ElHeader"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElMain: (typeof import("element-plus/es"))["ElMain"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElPagination: (typeof import("element-plus/es"))["ElPagination"];
    ElPopover: (typeof import("element-plus/es"))["ElPopover"];
    ElRadio: (typeof import("element-plus/es"))["ElRadio"];
    ElRow: (typeof import("element-plus/es"))["ElRow"];
    ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"];
    ElSpace: (typeof import("element-plus/es"))["ElSpace"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
    ElTable: (typeof import("element-plus/es"))["ElTable"];
    ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"];
    ElTabPane: (typeof import("element-plus/es"))["ElTabPane"];
    ElTabs: (typeof import("element-plus/es"))["ElTabs"];
    ElTag: (typeof import("element-plus/es"))["ElTag"];
    ElTooltip: (typeof import("element-plus/es"))["ElTooltip"];
    ErrorPage: (typeof import("./../components/ErrorPage/index.vue"))["default"];
    FormItem: (typeof import("./../components/ProForm/components/FormItem.vue"))["default"];
    Grid: (typeof import("./../components/Grid/index.vue"))["default"];
    GridItem: (typeof import("./../components/Grid/components/GridItem.vue"))["default"];
    Img: (typeof import("./../components/Upload/Img.vue"))["default"];
    Imgs: (typeof import("./../components/Upload/Imgs.vue"))["default"];
    ImportExcel: (typeof import("./../components/ImportExcel/index.vue"))["default"];
    Kbd: (typeof import("./../components/Kbd/index.vue"))["default"];
    Loading: (typeof import("./../components/Loading/src/Loading.vue"))["default"];
    Pagination: (typeof import("./../components/ProTable/components/Pagination.vue"))["default"];
    Popover: (typeof import("./../components/popover/index.vue"))["default"];
    ProFormBasics: (typeof import("./../components/ProForm/ProFormBasics.vue"))["default"];
    ProTable: (typeof import("./../components/ProTable/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SearchForm: (typeof import("./../components/SearchForm/index.vue"))["default"];
    SearchFormItem: (typeof import("./../components/SearchForm/components/SearchFormItem.vue"))["default"];
    SelectFilter: (typeof import("./../components/SelectFilter/index.vue"))["default"];
    SelectIcon: (typeof import("./../components/SelectIcon/index.vue"))["default"];
    SvgIcon: (typeof import("./../components/SvgIcon/index.vue"))["default"];
    SwitchDark: (typeof import("./../components/SwitchDark/index.vue"))["default"];
    TableColumn: (typeof import("./../components/ProTable/components/TableColumn.vue"))["default"];
    TreeFilter: (typeof import("./../components/TreeFilter/index.vue"))["default"];
    VirtualScroll: (typeof import("./../components/VirtualScroll/index.vue"))["default"];
    WangEditor: (typeof import("./../components/WangEditor/index.vue"))["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: (typeof import("element-plus/es"))["ElLoadingDirective"];
  }
}
